apiVersion: v1
kind: Service
metadata:
  name: {{ include "medflow.fullname" . }}-frontend
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
  labels:
    app: {{ include "medflow.fullname" . }}-frontend
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "medflow.fullname" . }}-frontend
  type: ClusterIP
