apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "medflow.fullname" . }}-frontend
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
  labels:
    app: {{ include "medflow.fullname" . }}-frontend
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ include "medflow.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "medflow.fullname" . }}-frontend
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          env:
            - name: NODE_ENV
              value: {{ .Values.global.environment | quote }}
            - name: PORT
              value: {{ .Values.frontend.port | quote }}
            - name: NEXT_TELEMETRY_DISABLED
              value: "1"
          ports:
            - containerPort: {{ .Values.frontend.port }}
              name: http
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: false # Next.js might write to temporary compilation folders (.next/cache)
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.basePath }}
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: {{ .Values.frontend.probes.initialDelaySeconds.liveness }}
            periodSeconds: {{ .Values.frontend.probes.periodSeconds.liveness }}
            timeoutSeconds: {{ .Values.frontend.probes.timeoutSeconds.liveness }}
            failureThreshold: {{ .Values.frontend.probes.failureThreshold.liveness }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.basePath }}
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: {{ .Values.frontend.probes.initialDelaySeconds.readiness }}
            periodSeconds: {{ .Values.frontend.probes.periodSeconds.readiness }}
            timeoutSeconds: {{ .Values.frontend.probes.timeoutSeconds.readiness }}
            failureThreshold: {{ .Values.frontend.probes.failureThreshold.readiness }}
