apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "medflow.fullname" . }}-uploads-claim
  namespace: {{ .Release.Namespace | default .Values.global.namespace }}
  labels:
    app: {{ include "medflow.name" . }}
    release: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.uploadsStorageSize }}
