global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager.medflow.svc.cluster.local:9093"

rule_files:
  - "alert-rules.yml"

scrape_configs:
  # 1. MedFlow Backend API metrics
  - job_name: "medflow-backend"
    metrics_path: "/api/metrics"
    static_configs:
      - targets: [ "medflow-backend.medflow.svc.cluster.local:4000" ]

  # 2. Redis Metrics (using redis-exporter)
  - job_name: "redis-exporter"
    static_configs:
      - targets: [ "redis-exporter.medflow.svc.cluster.local:9121" ]

  # 3. PostgreSQL Metrics (using postgres-exporter)
  - job_name: "postgres-exporter"
    static_configs:
      - targets: [ "postgres-exporter.medflow.svc.cluster.local:9187" ]

  # 4. Host OS Metrics (using node-exporter)
  - job_name: "node-exporter"
    static_configs:
      - targets: [ "node-exporter.medflow.svc.cluster.local:9100" ]
