apiVersion: v1
kind: Service
metadata:
  name: medflow-frontend
  namespace: medflow
  labels:
    app: medflow-frontend
spec:
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: medflow-frontend
  type: ClusterIP
