apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: medflow
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres
  clusterIP: None # Headless service for stateful identity management
