import { Controller, Post, Body, UseGuards, Req } from '@nestjs/common';
import { PaymentService } from './payment.service';
import { CreatePaymentIntentDto } from './dto/payment.dto';
import { JwtAuthGuard } from '../auth/jwt-auth.guard';
import { RolesGuard } from '../auth/roles.guard';
import { Roles } from '../auth/roles.decorator';
import { Role } from '@prisma/client';

@Controller('api/v2/payments')
@UseGuards(JwtAuthGuard, RolesGuard)
export class PaymentController {
  constructor(private readonly paymentService: PaymentService) {}

  @Post('checkout')
  // Depending on auth strategy, patients might just need JWT, without a specific system role.
  async createCheckoutSession(@Body() dto: CreatePaymentIntentDto, @Req() req: any) {
    const patientId = req.user.id;
    return this.paymentService.createIntent(dto, patientId);
  }

  @Post('link')
  @Roles(Role.RECEPTION, Role.ADMIN)
  async createPaymentLink(@Body() dto: CreatePaymentIntentDto, @Req() req: any) {
    // For payment links generated by receptionist, the patient ID needs to be determined
    // Usually, the bill is linked to the patient, but we might just pass patientId if needed.
    // For this flow, we will extract it from the Bill directly in the controller or pass it in DTO.
    // Let's pass the patientId in DTO or infer from the token if it's the patient.
    // Wait, receptionists call this. So req.user.id is the RECEPTIONIST's ID, not patient!
    // The previous `checkout` endpoint incorrectly used `req.user.id` as `patientId` if called by receptionist.
    return this.paymentService.createPaymentLink(dto, dto.patientId || req.user.id);
  }
}
